name: demoapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  bloc: ^8.1.2
  connectivity_plus: ^5.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^13.1.0
  google_fonts: ^6.1.0
  table_calendar: ^3.1.0
  wifi_info_flutter: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
